apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-metrics
  template:
    metadata:
      labels:
        app: sensor-metrics
    spec:
      containers:
      - name: sensor-metrics-container
        image: $DOCKER_IMAGE
        imagePullPolicy: Always
        env:
        - name: PHILIPS_HUE_URL
          value: $PHILIPS_HUE_URL
        - name: MOTION_SENSOR_ID
          value: "17"
        - name: LIGHT_LEVEL_SENSOR_ID
          value: "18"
        - name: TEMPERATURE_SENSOR_ID
          value: "19"
        - name: SENSOR_RELAY_URL
          value: $SENSOR_RELAY_URL
        - name: PORT
          value: "9101"
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-metrics
spec:
  ports:
  - name: http
    port: 9101
    protocol: TCP
    targetPort: 9101
  selector:
    app: sensor-relay
  